name: Deploy PWA to GitHub Pages (no-404)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Detect if Node build is needed
        id: detect
        run: |
          if [ -f "package.json" ]; then
            echo "need_build=true" >> $GITHUB_OUTPUT
          else
            echo "need_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        if: steps.detect.outputs.need_build == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        if: steps.detect.outputs.need_build == 'true'
        run: npm ci

      - name: Prisma generate (optional)
        if: steps.detect.outputs.need_build == 'true'
        run: npx prisma generate || true

      - name: Build app
        if: steps.detect.outputs.need_build == 'true'
        run: |
          # Sesuaikan dengan framework Anda. Default: npm run build
          npm run build

      - name: Pick output directory
        id: outdir
        run: |
          if [ -d "dist" ]; then
            echo "dir=dist" >> $GITHUB_OUTPUT
          elif [ -d "build" ]; then
            echo "dir=build" >> $GITHUB_OUTPUT
          elif [ -d "public" ]; then
            echo "dir=public" >> $GITHUB_OUTPUT
          else
            echo "Tidak ditemukan output. Pastikan proses build menghasilkan dist/ atau build/, atau sediakan folder public/."
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.outdir.outputs.dir }}

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
