name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: |
          if [ -f vite.config.ts ] || [ -f vite.config.js ]; then
            npm run build
            cp dist/index.html dist/404.html
          else
            npm run build
            cp build/index.html build/404.html
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        if: ${{ (hashFiles('vite.config.*') != '') }}
      
      - name: Deploy to GitHub Pages (CRA)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
        if: ${{ (hashFiles('vite.config.*') == '') }}
